"""
report_writer.py
================
Generates the Markdown V&V triage report from validation findings.

The report is structured the way a test engineer would file it: overall
verdict up front, summary counts, then each finding with expected vs.
actual behavior, possible cause, and recommended next step -- enough for
the person picking up the ticket to act without re-running the trace.
"""

from datetime import datetime

from rules_engine import Finding, PASS, FAIL, BLOCKED, INFO, worst_verdict

# Render order: failures first, then blocked, info, passes.
_VERDICT_ORDER = {FAIL: 0, BLOCKED: 1, INFO: 2, PASS: 3}


def build_report(findings: list, ecu: str, trace_file: str,
                 spec_file: str, spec_version: str = "") -> str:
    """Return the full Markdown report as a string."""
    overall = worst_verdict(findings) if findings else INFO
    counts = {v: sum(1 for f in findings if f.verdict == v)
              for v in (PASS, FAIL, BLOCKED, INFO)}

    lines = []
    add = lines.append
    add("# UDS V&V Triage Report")
    add("")
    add(f"| Field | Value |")
    add(f"|---|---|")
    add(f"| Module | {ecu} |")
    add(f"| Trace | {trace_file} |")
    add(f"| Spec | {spec_file} (v{spec_version}) |")
    add(f"| Generated | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |")
    add(f"| **Overall verdict** | **{overall}** |")
    add("")
    add(f"**Summary:** {counts[PASS]} PASS / {counts[FAIL]} FAIL / "
        f"{counts[BLOCKED]} BLOCKED / {counts[INFO]} INFO")
    add("")
    add("---")

    for f in sorted(findings,
                    key=lambda x: (_VERDICT_ORDER.get(x.verdict, 9),
                                   x.step if x.step is not None else 9999)):
        add("")
        step_txt = f" (trace step {f.step})" if f.step is not None else ""
        add(f"## {f.verdict} - {f.category}{step_txt}")
        add("")
        add(f"**Finding:** {f.message}")
        if f.expected:
            add("")
            add(f"**Expected behavior:** {f.expected}")
        if f.actual:
            add("")
            add(f"**Actual behavior:** {f.actual}")
        if f.possible_cause:
            add("")
            add(f"**Possible cause:** {f.possible_cause}")
        if f.next_step:
            add("")
            add(f"**Recommended next step:** {f.next_step}")

    add("")
    add("---")
    add("")
    add("*Generated by AutoSec UDS Conformance Workbench.*")
    add("")
    return "\n".join(lines)


def save_report(report_text: str, path: str) -> None:
    """Write the report to disk (UTF-8, LF endings)."""
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(report_text)
